name: console_app
description: A web app that uses AngularDart Components
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ngdart: ^8.0.0-dev.2
  ngforms: ^5.0.0-dev.1
  ngrouter: ^4.0.0-dev.1

dev_dependencies:
  ngtest: ^5.0.0-dev.1
  build_runner: ^2.4.0
  build_version: ^2.1.1
  build_test: ^2.2.0
  build_web_compilers: ^3.2.5
  lints: ^2.1.1
  meta: ^1.7.0
  test: ^1.24.3
