CREATE ROLE "edgebus-local-owner" WITH
LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION
CONNECTION LIMIT -1;

CREATE ROLE "edgebus-local-api" WITH
LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION
CONNECTION LIMIT -1;

CREATE ROLE "edgebus-local-readonly" WITH
LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION
CONNECTION LIMIT -1;

CREATE DATABASE "edgebus-local" WITH
OWNER = "edgebus-local-owner" ENCODING = 'UTF8'
CONNECTION LIMIT = -1;
